/* global describe, before, beforeEach, afterEach,it */
require('mocha-generators').install()

var Nightmare = require('..')
var chai = require('chai')
var server = require('./server')
var should = chai.should()
var koy = function () {
  koy()
  if (should) {
  }
}
describe('TEST Buy Harry Potter Book', function () {
  before(function (done) {
    server.listen(7500, done)
  })

  describe('nightmareJs and mocha and chai', function () {
    var nightmare

    beforeEach(function () {
      nightmare = Nightmare()
    })

    afterEach(function * () {
      yield nightmare.end()
    })

    it('ซื้อเล่ม 1 จำนวน 2 เล่ม, ซื้อเล่ม 2 จำนวน 1 เล่ม ส่วนลดต้องเท่ากับ 20', function * () {
      var case1 = yield nightmare
        .goto('http://localhost:5000')
        .wait(3000)
        .click('#b1')
        .click('#b1')
        .click('#b2')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case1.should.equal('20')
    })
    it('ซื้อเล่ม 1 จำนวน 2 เล่ม, ส่วนลดต้องเท่ากับ 0', function * () {
      var case0 = yield nightmare
        .goto('http://localhost:5000/')
        .wait(3000)
        .click('#b1')
        .click('#b1')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case0.should.equal('0')
    })
    it('ซื้อเล่ม 2 จำนวน 2 เล่ม, ส่วนลดต้องเท่ากับ 0', function * () {
      var case0 = yield nightmare
        .goto('http://localhost:5000/')
        .wait(3000)
        .click('#b2')
        .click('#b2')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case0.should.equal('0')
    })
    it('ซื้อเล่ม 2 จำนวน 3 เล่ม, ซื้อเล่ม 3 จำนวน 3 เล่ม ส่วนลดต้องเท่ากับ 60', function * () {
      var case2 = yield nightmare
        .goto('http://localhost:5000')
        .wait(3000)
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case2.should.equal('60')
    })
    it('ซื้อเล่ม 3 จำนวน 5 เล่ม, ซื้อเล่ม 4 จำนวน 4 เล่ม, เล่ม 5 จำนวน 3 ส่วนลดต้องเท่ากับ 200', function * () {
      var case3 = yield nightmare
        .goto('http://localhost:5000')
        .wait(3000)
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case3.should.equal('200')
    })
    it('ซื้อเล่ม 6 จำนวน 5 เล่ม, ซื้อเล่ม 7 จำนวน 4 เล่ม, ซื้อเล่ม 2 จำนวน 2 เล่ม, ซื้อเล่ม 3 จำนวน 1 เล่ม ส่วนลดต้องเท่ากับ 220', function * () {
      var case4 = yield nightmare
        .goto('http://localhost:5000/')
        .wait(2000)
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b2')
        .click('#b2')
        .click('#b1')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case4.should.equal('220')
    })
    it('ซื้อทุกเล่ม อย่างละ 1 เล่ม ส่วนลดต้องเท่ากับ 420 ', function * () {
      var case5 = yield nightmare
        .goto('http://localhost:5000')
        .wait(2000)
        .click('#b1')
        .click('#b2')
        .click('#b3')
        .click('#b4')
        .click('#b5')
        .click('#b6')
        .click('#b7')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case5.should.equal('420')
    })
    it('ซื้อเล่ม 1 จำนวน 2, เล่ม 4 จำนวน 5, เล่ม 6 จำนวน 1 เล่ม ส่วนลดต้องเท่ากับ 80', function * () {
      var case6 = yield nightmare
        .goto('http://localhost:5000')
        .wait(2000)
        .click('#b1')
        .click('#b1')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b6')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case6.should.equal('80')
    })
    it('ซื้อเล่ม 3 จำนวน 6, เล่ม 4 จำนวน 5, เล่ม 6 จำนวน 3 เล่ม ส่วนต้องเท่ากับ 220', function * () {
      var case7 = yield nightmare
        .goto('http://localhost:5000')
        .wait(2000)
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .wait(1000)
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case7.should.equal('220')
    })
    it('ซื้อ 1 จำนวน 4 เล่ม,เล่ม 2 จำนวน 4 เล่ม,เล่ม 3 จำนวน 4 ส่วนต้องเท่ากับ 240', function * () {
      var case8 = yield nightmare
        .goto('http://localhost:5000')
        .wait(1000)
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case8.should.equal('240')
    })
    it('ซื้อเล่ม 5 จำนวน 4 เล่ม,เล่ม 2 จำนวน 3 เล่ม,เล่ม 3 จำนวน 3 เล่ม,เล่ม 4 จำนวน 2 เล่ม ส่วนลดต้องเท่ากับ 300', function * () {
      var case9 = yield nightmare
        .goto('http://localhost:5000')
        .wait(1000)
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b4')
        .click('#b4')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case9.should.equal('300')
    })
    it('ซื้อเล่ม 5 จำนวน 4 เล่ม,เล่ม 6 จำนวน 8 เล่ม,เล่ม 3 จำนวน 3 เล่ม,เล่ม 4 จำนวน 3 เล่ม ส่วนลดต้องเท่ากับ 380', function * () {
      var case9 = yield nightmare
        .goto('http://localhost:5000')
        .wait(1000)
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case9.should.equal('380')
    })
    it('ซื้อเล่ม 2 จำนวน 2 เล่ม,เล่ม 6 จำนวน 5 เล่ม,เล่ม 3 จำนวน 3 เล่ม,เล่ม 4 จำนวน 5 เล่ม ส่วนลดต้องเท่ากับ 380', function * () {
      var case11 = yield nightmare
        .goto('http://localhost:5000')
        .wait(1000)
        .click('#b2')
        .click('#b2')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case11.should.equal('340')
    })
    it('ซื้อเล่ม 7 จำนวน 5 เล่ม,เล่ม 6 จำนวน 3 เล่ม,เล่ม 5 จำนวน 1 เล่ม ส่วนลดต้องเท่ากับ 380', function * () {
      var case11 = yield nightmare
        .goto('http://localhost:5000')
        .wait(1000)
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b5')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case11.should.equal('100')
    })
    it('ซื้อทุกเล่มอย่างละ 5 เล่ม ส่วนลดต้องเท่ากับ 2100', function * () {
      var case10 = yield nightmare
        .goto('http://localhost:5000')
        .wait(1000)
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case10.should.equal('2100')
    })
    it('ซื้อทุกเล่มอย่างละ 10 เล่ม ส่วนลดต้องเท่ากับ 4200', function * () {
      var case11 = yield nightmare
        .goto('http://localhost:5000')
        .wait(1000)
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b1')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b2')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b3')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b4')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b5')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b6')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .click('#b7')
        .evaluate(function () {
          this.price = document.querySelector('#discountTotal').innerHTML
          return this.price.substr(2, this.price.length - 1)
        })
      case11.should.equal('4200')
    })
  })
})
